<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.12.0 on win32)" generated="20231016 01:58:40.902" rpa="false" schemaversion="4">
<suite id="s1" name="Textpad" source="c:\Users\Danil Akulin\source\repos\TestUE\textpad.robot">
<test id="s1-t1" name="Открыть файл с Notepadd" line="9">
<kw name="Set Variable" library="BuiltIn">
<var>${file_path}</var>
<arg>C:\Users\Danil Akulin\Desktop\Test\Test.txt</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<msg timestamp="20231016 01:58:46.207" level="INFO">${file_path} = C:UsersDanil AkulinDesktopTestTest.txt</msg>
<status status="PASS" starttime="20231016 01:58:46.206" endtime="20231016 01:58:46.209"/>
</kw>
<kw name="Run" library="OperatingSystem">
<arg>notepad.exe</arg>
<doc>Runs the given command in the system and returns the output.</doc>
<msg timestamp="20231016 01:58:46.220" level="INFO">Running command 'notepad.exe 2&gt;&amp;1'.</msg>
<status status="PASS" starttime="20231016 01:58:46.209" endtime="20231016 01:59:02.262"/>
</kw>
<kw name="Sleep" library="BuiltIn">
<arg>2s</arg>
<doc>Pauses the test executed for the given time.</doc>
<msg timestamp="20231016 01:59:04.270" level="INFO">Slept 2 seconds</msg>
<status status="PASS" starttime="20231016 01:59:02.269" endtime="20231016 01:59:04.270"/>
</kw>
<kw name="Click" library="SikuliLibrary">
<arg>Ctrl</arg>
<doc>Click</doc>
<msg timestamp="20231016 01:59:08.099" level="INFO">[error] ImagePath: find: not there: Ctrl.png</msg>
<msg timestamp="20231016 01:59:08.099" level="INFO" html="true">&lt;img src='sikuli_captured/sikuliximage-1697446747803.png'/&gt;
[error] ImagePath: find: not there: Ctrl.png</msg>
<msg timestamp="20231016 01:59:08.099" level="FAIL">com.github.rainmanwy.robotframework.sikulilib.exceptions.TimeoutException: Timeout happened, could not find P(Ctrl.png -- not valid!) S: 0.7</msg>
<status status="FAIL" starttime="20231016 01:59:04.282" endtime="20231016 01:59:08.099"/>
</kw>
<kw name="Type">
<arg>o</arg>
<status status="NOT RUN" starttime="20231016 01:59:08.117" endtime="20231016 01:59:08.117"/>
</kw>
<kw name="Wait For Active Window">
<arg>Открыть</arg>
<status status="NOT RUN" starttime="20231016 01:59:08.124" endtime="20231016 01:59:08.125"/>
</kw>
<kw name="Send">
<arg>${file_path}</arg>
<status status="NOT RUN" starttime="20231016 01:59:08.128" endtime="20231016 01:59:08.128"/>
</kw>
<kw name="Send">
<arg>{ENTER}</arg>
<status status="NOT RUN" starttime="20231016 01:59:08.139" endtime="20231016 01:59:08.139"/>
</kw>
<status status="FAIL" starttime="20231016 01:58:46.205" endtime="20231016 01:59:08.139">com.github.rainmanwy.robotframework.sikulilib.exceptions.TimeoutException: Timeout happened, could not find P(Ctrl.png -- not valid!) S: 0.7</status>
</test>
<doc>Открыть файл с использованием Notepad</doc>
<status status="FAIL" starttime="20231016 01:58:40.908" endtime="20231016 01:59:08.143"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Textpad">Textpad</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231016 01:58:41.050" level="ERROR">Error in file 'c:\Users\Danil Akulin\source\repos\TestUE\textpad.robot' on line 3: Initializing library 'AutoItLibrary' with no arguments failed: com_error: (-2147221164, 'Class not registered', None, None)
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\win32com\client\dynamic.py", line 84, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147221021, 'Operation unavailable', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\AutoItLibrary\__init__.py", line 91, in __init__
    self._AutoIt = win32com.client.Dispatch("AutoItX3.Control")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\win32com\client\__init__.py", line 118, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch, userName, clsctx)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\win32com\client\dynamic.py", line 104, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\win32com\client\dynamic.py", line 86, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147221164, 'Class not registered', None, None)</msg>
</errors>
</robot>
